enum Unit {
  NUMBER
  GRAMS
}

type StoresItem {
  _id: ID!
  name: String!
  amount: Int!
  unit: Unit!
}

type RemoveStoresItemPayload {
  removed: Boolean!
  totalBefore: Int!
  totalAfter: Int!
  storesItem: StoresItem
}

type Query {
  "total number of stores items"
  totalStoresItems: Int
  "all stores items"
  allStoresItems: [StoresItem]
}

input AddStoresItemInput {
  name: String!
  amount: Int
  unit: Unit!
}

type Mutation {
  "add stores item"
  addStoresItem(input: AddStoresItemInput): StoresItem
  "remove stores item by _id"
  removeStoresItem(_id: ID!): RemoveStoresItemPayload
}
